node {
    checkout scm
    
     dir('jobs'){
         git branch: 'master',
             credentialsId: 'okbluesgithub',
             url: 'git@github.com:okrasnyiblues/randomtest.git'
     }

    jobDsl targets: [
        'jenkins/bootstrap/jobs.groovy'
    ].join('\n'),
            removedJobAction: 'DELETE',
            removedViewAction: 'DELETE',
            lookupStrategy: 'JENKINS_ROOT'

}

